name: CICD
 
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin 
      - name: Build docker image
        run: docker build -t myroslavpro/project-rest-service-cicd-with-actions .
      - name: Publish image to docker hub
        run: docker push myroslavpro/project-rest-service-cicd-with-actions:latest
        
  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Pull Image from docker hub
        run: docker pull myroslavpro/project-rest-service-cicd-with-actions:latest
      - name: Delete the old container
        run: docker rm -f project-rest-service-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name project-rest-service-container myroslavpro/project-rest-service-cicd-with-actions
